version: "2"

services:
  app:
    image: pottava/godep:go1.5
    command: go run /go/src/github.com/pottava/aws-s3-proxy/main.go
    ports:
      - 8080:80
    volumes:
      - .:/go/src/github.com/pottava/aws-s3-proxy
    working_dir: /go/src/github.com/pottava/aws-s3-proxy
    environment:
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET
      - BASIC_AUTH_USER
      - BASIC_AUTH_PASS
      - SSL_CERT_PATH
      - SSL_KEY_PATH
      - ACCESS_LOG=true
      - GO15VENDOREXPERIMENT=1
    container_name: app
